# Generated by Django 4.1.5 on 2023-02-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuarios_tfno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desarrollo', models.CharField(max_length=150)),
                ('investigacion', models.CharField(max_length=150)),
            ],
        ),
    ]
